site_name: DENGJIAJI âœ¦ BLOG
site_url: https://dengjiaji.github.io/self/
site_description: "dengjiaji's blog"
repo_url: https://github.com/Dengjiaji
repo_name: self

theme:
  name: shadcn
  image: figure/icon.jpg
  show_stargazers: true
  locale: zh_CN
  show_datetime: true

plugins:
  - search
  - excalidraw

nav:
  - about me: index.md
  - blog:
      # - Archives: blog/index.md
      - Proactive Agents : blog/2025-11-19.md

markdown_extensions:
  admonition:
  codehilite:
  fenced_code:
  footnotes:
  extra:
  pymdownx.blocks.details:
  pymdownx.tabbed:
  pymdownx.blocks.tab:
    combine_header_slug: true
    separator: ___
  pymdownx.progressbar:
  pymdownx.snippets:
  pymdownx.arithmatex:
    generic: true
  shadcn.extensions.echarts.alpha:
  shadcn.extensions.codexec:
  shadcn.extensions.iconify:

# pip install mkdocs-shadcn
# mkdocs build
# mkdocs serve
# mkdocs gh-deploy --force